version: '3.7'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"
    ports:
      - "9000:9000"
    network_mode: "bridge"